### ISSUE TITLE
16장

### ISSUE THREAD

**Issue by Youngminah** [MoSonLee/ComputerStructure#9]

**Comment by MoSonLee** [comment]
### Multi-Cycle Microarchitecture
- 각각의 명령어가 실행되는 만큼 실행됨
- 각각의 instruction마다 많은 clock cycle이 존재한다.

### 용어 정리
- State: programmer-visible state(개발자가 볼 수 있는 상태)(As, As')(As와 As' 중간은 볼 수없음)
- intermediate states들은 invisible state
- Single cycle: As -> As'
- Multiple cycle: As -> As+MS1 -> As+MS2 -> As+MS3 -> AS'

### Multi-Cycle Design
- 장점
   - Critical path design를 줄일 수 있다.
   - Bread and butter(common case) design
   - Balanced design: 명령어를 처리하는데 만약 5개 ALU가 필요하다면 Multi-cycle에선 공유해서 쓰면되기 떄문에 1개만 사용 가능 -> 밸런스가 좋아진다.
- control 시그널에 의해 stage(state) 변화가 이루어짐.
- 다음 상태에 대한 control signal은 현재 상태에서 준비한다.
- 명령어 사이클 처리는 **multiple** 다수의 state들로 나누어진다.
- state와 state 사이의 sequence(순차적으로) 연결시켜준다.
- control signal에 의해서 state가 결정된다.
- **control signal이 하는 일 두가지**
   - datapath의 동작을 제어해준다.
   - 다음 cycle의 control cycle를 미리 준비해준다.
   
### Microinstruction
- control signal이 현재의 state에서 하는 일들.
### Microsequencing
- 다음 상태에서 Microinstruction이 하는 일을 정해준다.
### Control store
- 모든 가능한 state를 위한 control signal을 저장해둔 것.
### Microsequencer
- 다음 cycle에서 사용될 control signal을 결정해준다.

### 현재 상태에서 control signal이 하는 두가지 일을 합치면?
- datapath와 microsequencer를 동시에 작동시킨다.
   - multiple cycle에서 control signal은 왜 현재 cycle에서 control cycle를 준비하지 않을까?
      - clock cycle를 줄이기 위해(critical path)를 줄이기 위해
      - dependent하지 않게 하기 위해
